[versions]
library-group = "io.github.remzoo.piwikprokmp"
library-version = "1.0.0"

android = "8.5.2"
kotlin = "2.2.0"
android-minSdk = "24"
android-compileSdk = "34"
piwik="2.1.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
piwik = { module = "pro.piwik:sdk-framework-android", version.ref = "piwik"}

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }